---
# tasks file for gnome
- name: "Including installation and setup"
  ansible.builtin.include_tasks: install.yml
  when:
    - not gnome_restore_defaults
  tags:
    - install

- name: "Including uninstall and restore defaults"
  ansible.builtin.include_tasks: uninstall.yml
  when:
    - gnome_restore_defaults|bool
  tags:
    - uninstall
