---
# tasks file for gnome
- name: "Including Theme Installation"
  ansible.builtin.include_tasks: install_theme.yml
  when: gnome_install_theme|bool

- name: "Including Theme Setup"
  ansible.builtin.include_tasks: setup_theme.yml
  when: gnome_enable_theme|bool

- name: "Including Theme Icon Installation"
  ansible.builtin.include_tasks: install_icon_theme.yml
  when: gnome_install_icon_theme|bool

- name: "Including Theme Icon Setup"
  ansible.builtin.include_tasks: setup_icon_theme.yml
  when: gnome_enable_icon_theme|bool
