---
# tasks file for gnome
- name: "Including Theme Installation"
  ansible.builtin.include_tasks: install_theme.yml
  when: gnome_install_theme|bool

- name: "Including Theme Setup"
  ansible.builtin.include_tasks: setup_theme.yml
  when: gnome_theme_enable|bool
